### ISSUE TITLE
clearing obsolete tier prices cannot work as implemented

### ISSUE THREAD

**Issue by ktruehl** [techdivision/import-product-tier-price#7]
In the TierPriceProcessor in the [`cleanUpTierPrices()`](https://github.com/techdivision/import-product-tier-price/blob/64bd55b513f1f3d1c4c3035b48b489d9d0b334f6/src/Services/TierPriceProcessor.php#L340) method, you perform the following check
```
if (isset($processedTierPrices[$tierPrice[MemberNames::VALUE_ID]]))
```
but this check can only evaluate to `true` if the tier price has actually been processed. So the following check
```
if (in_array($tierPrice[$this->getPrimaryKeyMemberName()], $processedTierPrices[$tierPrice[MemberNames::VALUE_ID]]))
```
must necessarily always evaluate to `true`, so the execution will always get to the `continue` statement and no tier prices are actually deleted.

There is a logical problem there. In order to be able to delete obsolete tier prices you necessarily need to explicitly look at the products that have been processed during the current import process. You could extract the product row IDs from the `$processedTierPrices` array and then check against those row IDs, but that would not cover the case where all tier prices for a product have been deleted.

We created the following patch: 
[bugfix-[2.0]--fix-deleting-of-obsolete-tier-prices.diff.zip](https://github.com/techdivision/import-product-tier-price/files/3182242/bugfix-.2.0.--fix-deleting-of-obsolete-tier-prices.diff.zip)

It's probably not the way you would do it (in particular passing the subject from the listener to the processor), but that was the quickest way I got the `cleanUpTierPrices()` to do what we need it to do.

Best,
Klaas

**Comment by wagnert** [comment]
@ktruehl Thanks for reporting. I'll have deeper look into that topic, as i thought i've tested it and it works. So i think i'll find the time during the next days and will come back to you as soon as possbible. My thoughts has been, that only tier prices of products that are part of the actual CSV file will be cleaned-up, all other's will not be touched. Is that the same behaviour you're expecting?

**Comment by wagnert** [comment]
@ktruehl Hi, found the time to have a look at the patch. I found three things that'll be a problem and i need to find solutions for

1. The patch only works for EE ('m sure you're aware about that)
2. The patch will not work in a standalone tier price import, it'll work if the tier price import is part of the product import 
3. The patch will only work if at least one SKU has tier prices (because the event `import_product_tier_price.listener.delete.obsolete.tier_prices`will only be fired if at least one tier price will be exported during the product import)

I think i've found a good solution, but i've to go the extra mile therefore. I'm actually test my implementation and can hopefully release it with 3.4.0.

**Comment by ktruehl** [comment]
Yeah. No time for general fixes. :)

Thanks for looking into this.
